// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {sprite} from '../models';

export function CancelGeneration():Promise<void>;

export function ChatPlan(arg1:string,arg2:string):Promise<main.ChatPlanResult>;

export function ClaudeStatus():Promise<main.ClaudeAuthInfo>;

export function ClearSession():Promise<void>;

export function CodexLogin():Promise<main.CodexAuthInfo>;

export function CodexStatus():Promise<main.CodexAuthInfo>;

export function DeleteGalleryImage(arg1:string):Promise<void>;

export function ExportProject(arg1:main.ExportArgs):Promise<string>;

export function GenerateAsset(arg1:main.GenerateAssetArgs):Promise<string>;

export function GenerateCharacter(arg1:main.GenerateCharacterArgs):Promise<string>;

export function GenerateCharacterRef(arg1:main.GenerateCharacterRefArgs):Promise<string>;

export function GenerateEdit(arg1:main.GenerateEditArgs):Promise<string>;

export function GenerateState(arg1:main.GenerateStateArgs):Promise<main.StateResult>;

export function GetGalleryPath():Promise<string>;

export function GetSettings():Promise<main.SettingsInfo>;

export function ListDirections():Promise<Array<sprite.DirectionInfo>>;

export function ListFolderImages(arg1:string):Promise<Array<main.GalleryImage>>;

export function ListGalleryImages():Promise<Array<main.GalleryImage>>;

export function ListPresets():Promise<Array<sprite.PresetInfo>>;

export function LoadImageFull(arg1:string):Promise<string>;

export function LoadImageThumb(arg1:string,arg2:number):Promise<string>;

export function LoadSession():Promise<string>;

export function MirrorFrames(arg1:Array<string>):Promise<Array<string>>;

export function PickFolder():Promise<string>;

export function PickImage():Promise<string>;

export function PixelizeImage(arg1:main.PixelizeImageArgs):Promise<string>;

export function RevealInFinder(arg1:string):Promise<void>;

export function SaveClaudeToken(arg1:string):Promise<void>;

export function SaveProviderKey(arg1:string,arg2:string):Promise<void>;

export function SaveProviderModel(arg1:string,arg2:string):Promise<void>;

export function SaveSession(arg1:string):Promise<void>;

export function SetProvider(arg1:string):Promise<void>;
