// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelGeneration() {
  return window['go']['main']['App']['CancelGeneration']();
}

export function ChatPlan(arg1, arg2) {
  return window['go']['main']['App']['ChatPlan'](arg1, arg2);
}

export function ClaudeStatus() {
  return window['go']['main']['App']['ClaudeStatus']();
}

export function ClearSession() {
  return window['go']['main']['App']['ClearSession']();
}

export function CodexLogin() {
  return window['go']['main']['App']['CodexLogin']();
}

export function CodexStatus() {
  return window['go']['main']['App']['CodexStatus']();
}

export function DeleteGalleryImage(arg1) {
  return window['go']['main']['App']['DeleteGalleryImage'](arg1);
}

export function ExportProject(arg1) {
  return window['go']['main']['App']['ExportProject'](arg1);
}

export function GenerateAsset(arg1) {
  return window['go']['main']['App']['GenerateAsset'](arg1);
}

export function GenerateCharacter(arg1) {
  return window['go']['main']['App']['GenerateCharacter'](arg1);
}

export function GenerateState(arg1) {
  return window['go']['main']['App']['GenerateState'](arg1);
}

export function GetGalleryPath() {
  return window['go']['main']['App']['GetGalleryPath']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ListDirections() {
  return window['go']['main']['App']['ListDirections']();
}

export function ListFolderImages(arg1) {
  return window['go']['main']['App']['ListFolderImages'](arg1);
}

export function ListGalleryImages() {
  return window['go']['main']['App']['ListGalleryImages']();
}

export function ListPresets() {
  return window['go']['main']['App']['ListPresets']();
}

export function LoadImageFull(arg1) {
  return window['go']['main']['App']['LoadImageFull'](arg1);
}

export function LoadImageThumb(arg1, arg2) {
  return window['go']['main']['App']['LoadImageThumb'](arg1, arg2);
}

export function LoadSession() {
  return window['go']['main']['App']['LoadSession']();
}

export function MirrorFrames(arg1) {
  return window['go']['main']['App']['MirrorFrames'](arg1);
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function PickImage() {
  return window['go']['main']['App']['PickImage']();
}

export function PixelizeImage(arg1) {
  return window['go']['main']['App']['PixelizeImage'](arg1);
}

export function RevealInFinder(arg1) {
  return window['go']['main']['App']['RevealInFinder'](arg1);
}

export function SaveClaudeToken(arg1) {
  return window['go']['main']['App']['SaveClaudeToken'](arg1);
}

export function SaveProviderKey(arg1, arg2) {
  return window['go']['main']['App']['SaveProviderKey'](arg1, arg2);
}

export function SaveProviderModel(arg1, arg2) {
  return window['go']['main']['App']['SaveProviderModel'](arg1, arg2);
}

export function SaveSession(arg1) {
  return window['go']['main']['App']['SaveSession'](arg1);
}

export function SetProvider(arg1) {
  return window['go']['main']['App']['SetProvider'](arg1);
}
